// Generated by https://quicktype.io

export interface PokemonResponse {
    count:    number;
    next:     string | null;
    previous: string | null;
    results:  Results[];
}

export interface Results {
    name: string;
    url: string;
}

export interface SmallPokemon extends Results {
    id:   string;
}
